site_name: My Docs
nav:
    - Home: index.md
    - Python:
      # - Detailed Design:
      # - Old boy python basic: python/New python file.md
      - My python: python/mypython.md
        # - User Experience: detailed_design/user_experience.md
        # - System Architecture:
        #   - Architecture overview: detailed_design/system_architecture.md
        #   - Forecasting service API: detailed_design/forecasting_service.md
        # - Data Management: detailed_design/data_management.md
        # - Production Forecasting: detailed_design/production_forecasting.md
        # - References: detailed_design/references.md
        # - UX design: ux-ui-design/ux-design.md
    - Java:
      - My Java: Java/myjava.md
        # - Machine Learning :
        #   - Grouping Strategy for Production Data: machine_learning/grouping.md
        #   - Validation Strategy for Production Forecasting: machine_learning/validation_strategy.md
        #   - Training Pipeline: machine_learning/ml_training_pipeline.md
        #   - Attempts to Remove Outliers Using Autoencoder: machine_learning/autoencoder/autoencoder.md
        # - Data Quality:
        #   - Data Preprocessing for Production Forecasting: Zhili/Zhili_outlier_detection_and_cleansing.md
        #   - Phase period matching in production life span: Zhili/period_match/Period_Match_pipeline.md
    # - Well Integrity Management Solution:
    #     - Data Model: wim/wim_data_model.md
    - C ++:
      - My C++ Notes: CPP/my_CPP.md
    - Algorithms:
      - By data structure: alog/data_struc.md
      # - List: alog/list/list.md
      # - Queue: alog/queue/queue.md
      # - tree: alog/tree/tree.md
      # - graph: algo/graph/graph.md
    - Cloud:
      - My cloud: cloud/mesh.md
    - Other things (listed by date):
      - Other CS stuff: other/mynote.md
    - Learn the fucking English:
      - my English notes: english/english_note.md
    - Health:
      - Health is important!: health/health.md
theme: readthedocs
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js